version: '2'

services:
  web:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: appr_roundrobin
    networks:
        net:
            ipv4_address: 102.24.0.6
    ports:
        - "34005:6000"
networks:
    net:
        ipam:
            driver: default
            config:
                - subnet: 102.24.0.0/16
volumes:
    mongodb:
    mongodb_config: